# List of all cops and their description/default values is available here:
#   https://github.com/bbatsov/rubocop/blob/master/manual/cops.md

AllCops:
  TargetRubyVersion: 2.5.3

# ==================================== Department Bundler ==========================================

Bundler/OrderedGems:
  Enabled: false

# ===================================== Department Layout ==========================================

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Layout/EmptyLinesAroundBlockBody:
  Description: "Keeps track of empty lines around block bodies."
  Enabled: false

Layout/EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: true

Layout/EndOfLine:
  Description: 'Use Unix-style line endings.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#crlf'
  Enabled: true

Layout/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# ==================================== Department Metrics ==========================================

Metrics/AbcSize:
  Max: 15 # Default is 15

Metrics/ClassLength:
  Max: 100 # Default is 100

Metrics/LineLength:
  Max: 100 # Default is 80
  Exclude:
    - config/schedule.rb

Metrics/MethodLength:
  Max: 10 # Default is 10

Metrics/ModuleLength:
  Max: 100 # Default is 100

Metrics/ParameterLists:
  Max: 5 # Default is 5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/routes.rb
    - config/initializers/secure_headers.rb

# ===================================== Department Naming ==========================================

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

# ===================================== Department Style ===========================================

Style/Alias:
  Description: 'Advise the use of alias_method over the alias keyword whenever possible.'
  Enabled: true

Style/CollectionMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/GlobalVars:
  Description: 'Do not introduce global variables.'
  StyleGuide: '#instance-vars'
  Reference: 'http://www.zenspider.com/Languages/Ruby/QuickRef.html'
  AllowedVariables:
    - $redis
    - $redis_cache
    - $redis_rollout
  Enabled: true

Style/OneLineConditional:
  Enabled: false

Style/SignalException:
  Description: 'This cop checks for uses of fail and raise.'
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-w'
  Enabled: false
